package com.example.user.greendaolibrary.entity;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.user.greendaolibrary.entity.LockMark;
import com.example.user.greendaolibrary.entity.Picture;

import com.example.user.greendaolibrary.entity.LockMarkDao;
import com.example.user.greendaolibrary.entity.PictureDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig lockMarkDaoConfig;
    private final DaoConfig pictureDaoConfig;

    private final LockMarkDao lockMarkDao;
    private final PictureDao pictureDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        lockMarkDaoConfig = daoConfigMap.get(LockMarkDao.class).clone();
        lockMarkDaoConfig.initIdentityScope(type);

        pictureDaoConfig = daoConfigMap.get(PictureDao.class).clone();
        pictureDaoConfig.initIdentityScope(type);

        lockMarkDao = new LockMarkDao(lockMarkDaoConfig, this);
        pictureDao = new PictureDao(pictureDaoConfig, this);

        registerDao(LockMark.class, lockMarkDao);
        registerDao(Picture.class, pictureDao);
    }
    
    public void clear() {
        lockMarkDaoConfig.getIdentityScope().clear();
        pictureDaoConfig.getIdentityScope().clear();
    }

    public LockMarkDao getLockMarkDao() {
        return lockMarkDao;
    }

    public PictureDao getPictureDao() {
        return pictureDao;
    }

}
