package com.example.user.greendaolibrary.entity;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.user.greendaolibrary.entity.LockMark;

import com.example.user.greendaolibrary.entity.LockMarkDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig lockMarkDaoConfig;

    private final LockMarkDao lockMarkDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        lockMarkDaoConfig = daoConfigMap.get(LockMarkDao.class).clone();
        lockMarkDaoConfig.initIdentityScope(type);

        lockMarkDao = new LockMarkDao(lockMarkDaoConfig, this);

        registerDao(LockMark.class, lockMarkDao);
    }
    
    public void clear() {
        lockMarkDaoConfig.getIdentityScope().clear();
    }

    public LockMarkDao getLockMarkDao() {
        return lockMarkDao;
    }

}
