package com.example.user.greendaolibrary.entity;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.user.greendaolibrary.entity.LockMark;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "LOCK_MARK".
*/
public class LockMarkDao extends AbstractDao<LockMark, Long> {

    public static final String TABLENAME = "LOCK_MARK";

    /**
     * Properties of entity LockMark.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property LockID = new Property(1, String.class, "lockID", false, "LOCK_ID");
        public final static Property LockName = new Property(2, String.class, "lockName", false, "LOCK_NAME");
        public final static Property PictureId = new Property(3, Long.class, "pictureId", false, "PICTURE_ID");
    };

    private DaoSession daoSession;


    public LockMarkDao(DaoConfig config) {
        super(config);
    }
    
    public LockMarkDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"LOCK_MARK\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"LOCK_ID\" TEXT," + // 1: lockID
                "\"LOCK_NAME\" TEXT," + // 2: lockName
                "\"PICTURE_ID\" INTEGER);"); // 3: pictureId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"LOCK_MARK\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, LockMark entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String lockID = entity.getLockID();
        if (lockID != null) {
            stmt.bindString(2, lockID);
        }
 
        String lockName = entity.getLockName();
        if (lockName != null) {
            stmt.bindString(3, lockName);
        }
 
        Long pictureId = entity.getPictureId();
        if (pictureId != null) {
            stmt.bindLong(4, pictureId);
        }
    }

    @Override
    protected void attachEntity(LockMark entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public LockMark readEntity(Cursor cursor, int offset) {
        LockMark entity = new LockMark( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // lockID
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // lockName
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3) // pictureId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, LockMark entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setLockID(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setLockName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setPictureId(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(LockMark entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(LockMark entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getPictureDao().getAllColumns());
            builder.append(" FROM LOCK_MARK T");
            builder.append(" LEFT JOIN PICTURE T0 ON T.\"PICTURE_ID\"=T0.\"PICTURE_ID\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected LockMark loadCurrentDeep(Cursor cursor, boolean lock) {
        LockMark entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Picture picture = loadCurrentOther(daoSession.getPictureDao(), cursor, offset);
        entity.setPicture(picture);

        return entity;    
    }

    public LockMark loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<LockMark> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<LockMark> list = new ArrayList<LockMark>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<LockMark> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<LockMark> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
